### ISSUE TITLE
The rouge highlighter UI breaks when linenos option turned ON

### ISSUE THREAD

**Issue by rampatra** [rohanchandra/type-theme#40]
Preview:
<img width="796" alt="screen shot 2016-12-10 at 23 40 51" src="https://cloud.githubusercontent.com/assets/2862724/21076947/2134aaa8-bf32-11e6-9836-cf12f27d6e84.png">
Live Demo: http://java.ramswaroop.me/2015/06/30/constructors.html

**Comment by rohanchandra** [comment]
Thanks for the report.

This is caused as `table` is forced to 100% width, and Rouge uses the `table` for the line number feature.

I'll add in this work-around, since I normally want full-width tables:

```
/* Work-around for Rouge highlighter */
pre table {
    width: inherit;
} 
```

Or we could maybe use a CSS flexbox so `.code` takes up the remaining space after the line numbers?

**Comment by rampatra** [comment]
Great! Thanks for such quick response.
