### ISSUE TITLE
Add Search Support

### ISSUE THREAD

**Issue by saden1** [rohanchandra/type-theme#51]
Would be nice if the the site could be searched.

See https://learn.cloudcannon.com/jekyll/jekyll-search-using-lunr-js/

**Comment by sylhare** [comment]
Allo,

I worked on customizing type-theme (because this theme is awesome!) and I've looked into adding a search feature. I've tried with [Simple-Jekyll-Search](https://github.com/christian-fei/Simple-Jekyll-Search) and [lunr.js](https://lunrjs.com/). 

However I used bootstrap to make it look good (which is not used on this theme).  I had plans to go back at it, so once I have something good enough I'll make a pull request 😉

**Comment by rohanchandra** [comment]
@saden1 Search is now included in Type Theme thanks to @Sylhare! 🎉

**Comment by saden1** [comment]
Yay. Great work!
