### ISSUE TITLE
Dates in English

### ISSUE THREAD

**Issue by augusto-garcia** [rohanchandra/type-theme#7]
Another point, the dates of posts are still in English (although translating the other parts was quite easily). http://augusto-garcia.github.io/Biometria-de-Marcadores/

Is there a way to have them in another languages (e. g. Portuguese)?

Thanks.

**Comment by rohanchandra** [comment]
It does not appear there is an easy way to localize dates in Jekyll because Github Pages does not support custom plug-ins.

http://alanwsmith.com/jekyll-liquid-date-formatting-examples has instructions on date formatting which you can follow to change how dates display.

You can edit date formatting in Type by opening `post.html` in the `_layouts` folder and changing the lines which reads `{{ page.date | date: "%B %-d, %Y" }}` to your preferred format.

**Comment by augusto-garcia** [comment]
Thanks again. It worked smoothly for posts, but on the main page, date format is still in English. Where should I change it for the main page?

**Comment by rohanchandra** [comment]
For the main page, open `main.html` and change the same section which reads `{{ post.date | date: "%B %-d, %Y" }}` to match your configuration in `post.html`.

**Comment by augusto-garcia** [comment]
Yes, it worked. Thanks.
